Feature/ob4
727-Ventures/openbrush-website pull request #63
Opened 2023-07-10 18:48 UTC by varex83

2023-07-13 08:56 UTC, o-tsaruk commented on data/generators/extensions.js
> +      // accessControlEnumerableExtension.addConstructorAction('_instance._init_with_admin(_instance.env().caller());')
do we need this comment?

2023-07-13 08:57 UTC, o-tsaruk submitted a review, later dismissed

2023-07-13 10:50 UTC, coreggon11 requested changes
gj, left small comments

2023-07-13 10:50 UTC, coreggon11 commented on components/WizardOutput.js
> +    inkVersion: '4.1.0',
should be 4.2.1

2023-07-13 10:50 UTC, coreggon11 commented on components/WizardOutput.js
> +  'v4.0.0': {
should be 4.0.0-beta for now

2023-07-13 10:50 UTC, coreggon11 commented on components/Wizard.js
> +                      <option value="v4.0.0">v4.0.0</option>
should be 4.0.0-beta for now

2023-07-20 08:50 UTC, coreggon11 approved these changes

2023-07-20 16:18 UTC, merged